###
GET http://localhost:8080/api-docs
###
GET http://localhost:8080/contacts/66469af6c0d8a23c38387e1c
###
GET http://localhost:8080/contacts/66469b47c0d8a23c38387e1d
###
GET http://localhost:8080/contacts/66469be5c0d8a23c38387e1e

###
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Scarlett",
  "lastName": "Johansson",
  "email": "johanssonS2@test.com",
  "favoriteColor": "Black",
  "birthday": "11/22/1984"

}


###
PUT http://localhost:8080/contacts/66469b47c0d8a23c38387e1d
Content-Type: application/json

{
  "firstName": "Robert",
  "lastName": "Downey Jr.",
  "email": "Rdowny@test.com",
  "favoriteColor": "Red",
  "birthday": "04/04/1965"

}

###
DELETE http://localhost:8080/contacts/66469d87c0d8a23c38387e20