GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/66343a7d3815be2afb1cede0
###
GET http://localhost:8080/contacts/66343a7d3815be2afb1cede1
###
GET http://localhost:8080/contacts/66343a7d3815be2afb1cede2

###
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "name": "Chris Evans",
  "email": "cEvans@test.com",
  "phone": "1234567890",
  "favoriteColor": "Blue",
  "birthday": "06/13/1981"
}
###
GET http://localhost:8080/contacts/66401ba1ece33d2fdb5d11ff

###
PUT http://localhost:8080/contacts/66401ba1ece33d2fdb5d11ff
Content-Type: application/json

{
   "name": "Chris Evans",
  "email": "cEvans@test.com",
  "phone": "1234567891",
  "favoriteColor": "Blue",
  "birthday": "06/13/1981"

}

###
DELETE http://localhost:8080/contacts/663f8a80459cfe349b856f08